name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: npm ci && npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TURBO_164D0 }}
          channelId: live
          projectId: turbo-164d0

      - name: Send deploy notification to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)
          jq -n \
            --arg repo "$GITHUB_REPOSITORY" \
            --arg url "https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}" \
            --arg commit "${GITHUB_SHA}" \
            --arg timestamp "$TIMESTAMP" \
            '{
              "embeds": [{
                "title": "🚀 Docs updated!",
                "description": ("Project **\($repo)** has been deployed."),
                "color": 7506394,
                "fields": [
                  {"name": "Commit", "value": "[\($commit)](\($url))"}
                ],
                "footer": { "text": "Firebase Deploy" },
                "timestamp": $timestamp
              }]
            }' > payload.json

          curl -H "Content-Type: application/json" \
            -X POST \
            -d @payload.json \
            "$DISCORD_WEBHOOK"
